services:
  - type: web
    name: nextjs
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: NEXT_PUBLIC_GEMINI_API_KEY
        sync: false
    autoDeploy: true
    branch: main
    healthCheckPath: /
    healthCheckTimeout: 300
